import json
import os

import pandas as pd
import requests

from dotenv import load_dotenv
from mistralai.client import Mistral


# ==========================================================
# CONFIGURATION
# ==========================================================

API_URL = "http://127.0.0.1:8000/ask"

ANNOTATED_DATASET = "data/annotated_dataset.json"

CSV_OUTPUT = "evaluation_results.csv"

JSON_OUTPUT = "evaluation_results.json"


# ==========================================================
# API KEY
# ==========================================================

load_dotenv()

api_key = os.getenv("MISTRAL_API_KEY")

if api_key is None:
    raise ValueError("MISTRAL_API_KEY not found")


client = Mistral(api_key=api_key)


# ==========================================================
# LOAD DATASET
# ==========================================================

with open(ANNOTATED_DATASET, "r", encoding="utf-8") as f:
    annotated_dataset = json.load(f)


# ==========================================================
# CALL YOUR RAG API
# ==========================================================

def call_rag(question):

    response = requests.post(
        API_URL,
        json={
            "question": question,
            "k": 5
        },
    )

    response.raise_for_status()

    return response.json()


# ==========================================================
# ASK MISTRAL TO EVALUATE
# ==========================================================

def evaluate_with_mistral(question, expected, answer):

    prompt = f"""
You are an expert evaluator.

Question:
{question}

Expected answer:
{expected}

Answer generated by the RAG:
{answer}

Evaluate the generated answer.

Give:

Faithfulness (0-10)

Relevance (0-10)

Completeness (0-10)

Correctness (0-10)

Then write one short explanation.

Return ONLY valid JSON like:

{{
"faithfulness": 9,
"relevance": 8,
"completeness": 9,
"correctness": 10,
"comment": "..."
}}
"""

    response = client.chat.complete(

        model="mistral-small-latest",

        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],

        temperature=0

    )

    return response.choices[0].message.content


# ==========================================================
# MAIN LOOP
# ==========================================================

results = []

print("=" * 70)
print("Evaluating...")
print("=" * 70)

for sample in annotated_dataset:

    question = sample["question"]

    expected = sample["expected_answer"]

    rag = call_rag(question)

    answer = "\n".join(

        r["title"]

        for r in rag["results"]

    )

    print(question)

    judgement = evaluate_with_mistral(
        question,
        expected,
        answer,
    )

    try:

        scores = json.loads(judgement)

    except Exception:

        scores = {
            "faithfulness": None,
            "relevance": None,
            "completeness": None,
            "correctness": None,
            "comment": judgement
        }

    scores["question"] = question

    scores["expected"] = expected

    scores["answer"] = answer

    results.append(scores)


# ==========================================================
# SAVE
# ==========================================================

df = pd.DataFrame(results)

df.to_csv(
    CSV_OUTPUT,
    index=False,
    encoding="utf-8",
)

with open(
    JSON_OUTPUT,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        results,
        f,
        indent=4,
        ensure_ascii=False,
    )


# ==========================================================
# SUMMARY
# ==========================================================

print()

print(df)

print()

print(df.select_dtypes("number").mean())

print()

print("Saved")

print(CSV_OUTPUT)

print(JSON_OUTPUT)